services:
  homepage:
    container_name: homelab-homepage
    image: ghcr.io/benphelps/homepage:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - ./config:/app/config
      - ./icons:/app/public/icons
    ports:
      - "3100:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true
    name: homelab-network
