services:
  dashy:
    container_name: homelab-dashy
    image: lissy93/dashy:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - ./config:/app/public
    ports:
      - "3101:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - homelab-network

networks:
  homelab-network:
    external: true
    name: homelab-network
