version: '3.8'

services:
  autoheal:
    container_name: homelab-autoheal
    image: willfarrell/autoheal:latest
    restart: always
    env_file:
      - .env
    environment:
      TZ: ${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "ps", "aux"]
      interval: 60s
      timeout: 10s
      retries: 3
    networks:
      - homelab-network
    depends_on:
      docker-proxy:
        condition: service_healthy

networks:
  homelab-network:
    external: true
    name: homelab-network
